### ISSUE TITLE
Invalid date

### ISSUE THREAD

**Issue by HengGeZai** [cute-jumper/gscholar-bibtex#16] opened 2016-09-24 17:51 UTC
Hi, when I queried google scholar in China, it showed "error in process sentinel: Invalid date: 六, 24 9月 2016 18:47:24.00 GMT".
![2016-09-25 01-45-18](https://cloud.githubusercontent.com/assets/17907484/18810180/48cf147e-82c2-11e6-958f-f56383d20f82.png)
![2016-09-25 01-48-02](https://cloud.githubusercontent.com/assets/17907484/18810181/48d21868-82c2-11e6-9f95-05de6626f438.png)

**Comment by cute-jumper** [comment] 2016-09-26 19:30
Hmm...Looking like an encoding problem in the cookie. Thanks for reporting and I'll take a look at it later.

**Comment by cute-jumper** [comment] 2016-09-26 21:07
I actually can't reproduce your problem. After setting the locale to `zh_CN.UTF-8` to get the date just as you showed, `gscholar-bibtex` still works fine.

Can you try the following code to see whether it can eliminate the bug? Evaluate the function below and run `gscholar-bibtex`.

```
(defun gscholar-bibtex-google-scholar-search-results (query)
  (let* ((url-request-method "GET")
         (system-time-locale "C")
	 ;; Fabricate a cookie with a random ID that expires in an hour.
         (random-id (format "%016x" (random (expt 16 16))))
         (expiration (format-time-string "%a, %d %b %Y %H:%M:%S.00 %Z"
					 (time-add (current-time)
						   (seconds-to-time 3600)) t))
         (my-cookie (mapconcat #'identity
			       (list (format "GSP=ID=%s:CF=4; " random-id)
				     (format "expires=%s" expiration)
				     "path=/"
				     "domain=scholar.google.com")
			       "; ")))
    (let ((url-current-object
	   (url-generic-parse-url "http://scholar.google.com") ))
      (url-cookie-handle-set-cookie my-cookie))
    (gscholar-bibtex--url-retrieve-as-string
     (concat "http://scholar.google.com/scholar?q="
	     (url-hexify-string
	      (replace-regexp-in-string " " "\+" query))))))
```

**Comment by HengGeZai** [comment] 2016-09-27 03:52
Thanks @cute-jumper .  The code can eliminate the bug when I change "http://" to "https://".

    (defun gscholar-bibtex-google-scholar-search-results (query)
      (let* ((url-request-method "GET")
         (system-time-locale "C")
     ;; Fabricate a cookie with a random ID that expires in an hour.
         (random-id (format "%016x" (random (expt 16 16))))
         (expiration (format-time-string "%a, %d %b %Y %H:%M:%S.00 %Z"
                     (time-add (current-time)
                           (seconds-to-time 3600)) t))
         (my-cookie (mapconcat #'identity
                   (list (format "GSP=ID=%s:CF=4; " random-id)
                     (format "expires=%s" expiration)
                     "path=/"
                     "domain=scholar.google.com")
                   "; ")))
    (let ((url-current-object
       (url-generic-parse-url "https://scholar.google.com") ))
      (url-cookie-handle-set-cookie my-cookie))
    (gscholar-bibtex--url-retrieve-as-string
     (concat "https://scholar.google.com/scholar?q="
         (url-hexify-string
          (replace-regexp-in-string " " "\+" query))))))

**Comment by cute-jumper** [comment] 2016-09-27 20:03
Can you confirm that if you change the "http" to "https" in the current code (which means you use the original code in your `gscholar-bibtex.el` file, not the code above), it still works? You can search and replace the "http" with "https" in `gscholar-bibtex.el` file.

**Comment by HengGeZai** [comment] 2016-09-28 09:25
I use a modified host file instead of VPN. So, I have to change the "http" to "https", when I use google scholar in China. For example, in firefox browser:
Use https:
![screenshot from 2016-09-28 09-30-48](https://cloud.githubusercontent.com/assets/17907484/18904676/f2244964-8591-11e6-9ffb-6a748f07e44b.png)

Use http:
![screenshot from 2016-09-28 09-31-46](https://cloud.githubusercontent.com/assets/17907484/18904675/f188b38c-8591-11e6-8ae5-757e308d8684.png)

In emacs, I change the "http" to "https" in the current code(the original code in gscholar-bibtex.el) like this:

    (defun gscholar-bibtex-google-scholar-search-results (query)
      (let* ((url-request-method "GET")
	 ;; Fabricate a cookie with a random ID that expires in an hour.
         (random-id (format "%016x" (random (expt 16 16))))
	 (expiration (format-time-string "%a, %d %b %Y %H:%M:%S.00 %Z"
					 (time-add (current-time)
						   (seconds-to-time 3600)) t))
         (my-cookie (mapconcat #'identity
			       (list (format "GSP=ID=%s:CF=4; " random-id)
				     (format "expires=%s" expiration)
				     "path=/"
				     "domain=scholar.google.com")
			       "; ")))
        (let ((url-current-object
	   (url-generic-parse-url "https://scholar.google.com") ))       ; change the "http" to "https" 
       (url-cookie-handle-set-cookie my-cookie))
     (gscholar-bibtex--url-retrieve-as-string
      (concat "https://scholar.google.com/scholar?q="                    ; change the "http" to "https" 
	     (url-hexify-string
	      (replace-regexp-in-string " " "\+" query))))))

It still show "Invalid date: 三, 28 9月 2016 09:47:37.00 GMT".
If add `(system-time-locale "C")` after `(let* ((url-request-method "GET")` and change the "http" to "https" at the same time, the bug is eliminated.

Here is my hosts file, ".txt" should be omited

[hosts.txt](https://github.com/cute-jumper/gscholar-bibtex/files/497605/hosts.txt)

**Comment by cute-jumper** [comment] 2016-09-28 17:43
Looks more like a networking problem. Can you really get the data from Google Scholar from inside Emacs? Say, using the following code, what response can you get from the server?

```
(url-retrieve "https://scholar.google.com/scholar?q=test"
              (lambda (status) (switch-to-buffer (current-buffer))))
```

**Comment by HengGeZai** [comment] 2016-09-29 14:57
Here is the result of 

    (url-retrieve "https://scholar.google.com/scholar?q=test"
              (lambda (status) (switch-to-buffer (current-buffer))))

[result.txt](https://github.com/cute-jumper/gscholar-bibtex/files/500915/result.txt)

And I think the result is similar to `M-x eww RET https://scholar.google.com/scholar?q=test `

![2016-09-29 22-37-41](https://cloud.githubusercontent.com/assets/17907484/18958484/5f436f6c-8695-11e6-8d3c-cc3ff6524a6f.png)

Today, I use a free VPN to test my network. Gscholar works well, both "http" and "https", if I add `(system-time-locale "C")`

So, I think  `(system-time-locale "C")` can eliminate the bug, and I should use a VPN to get the result.

Thanks for your warm help.

**Comment by cute-jumper** [comment] 2016-09-29 18:56
Yep. Good to know it works. I've pushed the fix of the locale.

**Closed by cute-jumper** 2016-09-29 18:56 UTC
